### PR TITLE
Python 3.4 support

### PR DESCRIPTION
**Pull request by skoczen**
Hey @rdegges ,

Thanks for this and all the other django-heroku projects. They make my life easier on a monthly basis. :)

Here's support for python 3.4 - let me know if you'd like anything different to get this merged!

-Steven

### CODE REVIEW

**Comment by rdegges** [comment]
Thanks, I'll work on getting this in =)

**Comment by rdegges** [comment]
Ok -- all merged. I also cut a new release, so if you install the latest version of the library it'll be 2.7 -> 3.4 compatible.

Thanks so much!

**Comment by skoczen** [comment]
Looking great - thanks for the quick turn around!

On a side note, I've been digging the fact that you're both a programmer, a writer, and a person all in one, publicly, for years.  You're one of the folks that really inspire me.  Figured you should know.

-Steven

**Comment by rdegges** [comment]
Thanks man! Always happy to hear stuff like this <33 Makes all the hard work worth it ^^

**Pull request merged**
